import type { Metadata } from 'next';
import './globals.css';
import { Layout } from './components/Layout';
import { ptSerif } from './utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body className={ptSerif.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
