import type { Metadata } from 'next';
import './globals.css';
import { Layout } from './components/Layout';
import { PT_Serif, Meow_Script } from 'next/font/google';

const ptSerif = PT_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-serif',
});

const meowScript = Meow_Script({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-script',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body className={`${ptSerif.variable} ${meowScript.variable}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
